title: Osny Netto - Front-end developer and UI Designer
email: netto@osny.me
baseurl: ""
url: "http://www.osny.me"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:title
      comments: true

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/