# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Osny Netto - Front-end developer and UI Designer
email: netto@osny.me
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.osny.me" # the base hostname & protocol for your site
# twitter_username: osnysantos
# github_username:  osnysantos

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:title
      comments: true


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/